[package]
name = "effector-swc-plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"
once_cell = "1.10.0"
regex = { version = "1.5.5", features = ["std", "perf"], default-features = false }
serde = { version = "1", features = ["derive"] }
swc_atoms = "0.2.11"
swc_common = { version = "0.17.24", features = ["concurrent"] }
swc_ecmascript = { version = "0.148.0", features = ["utils", "visit"] }
tracing = "0.1.32"

[dev-dependencies]
serde_json = "1.0.79"
swc_ecma_transforms_testing = "0.81.0"
swc_ecmascript = { version = "0.148.0", features = ["parser", "transforms"] }
testing = "0.19.1"
