name: Publish CI

on: [push]

jobs:
  publish-to-crates:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Install Taplo
        if: false
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: tamasfe/taplo
          tag: "0.8.0"
          extension: "\\.gz"
          rename-to: taplo.gz
          arch: x86_64
      
      - name: Decompress Taplo
        if: false
        run: |
          TAPLO=$(which taplo);
          gzip -d $TAPLO 2> echo
      
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install rust
        uses: actions-rs/toolchain@v1
        
      - name: Install Taplo
        uses: actions-rs/cargo@v1
        with:
          command: install taplo-cli --locked
      
      - run: "echo $(taplo get -f Cargo.toml 'package.version')"
      
        
