name: Publish CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install rust
        uses: actions-rs/toolchain@v1
  
  toml:
    runs-on: ubuntu-22.04
    needs: [setup]
    steps:
      - name: Install TOML Cli
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: toml-cli --locked
      - run: "echo $(toml get Cargo.toml 'package.version')"
  
  build:
    runs-on: ubuntu-22.04
    needs: [setup]
    steps:
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      
      - name: Tet
        uses: actions-rs/cargo@v1
        with:
          command: test
  
  set_version:
    runs-on: ubuntu-22.04
    needs: [toml, build]
    steps:
      - name: Set version
        run: toml set Cargo.toml "package.version" "0.1.0"
      
      - name: Get version
        run: "echo $(toml get Cargo.toml 'package.version')"
